name: NNC Admin Panel ERP

on:
  push:
    branches: ['master']
  # pull_request:
  #   branches: [ "release-development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for System Updates
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --production

      - name: Install TypeScript globally
        run: yarn global add typescript

      - name: Build app
        run: yarn build

      - name: Upload to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://$AWS_S3_BUCKET --delete --acl public-read --exclude '.well-known/*'

      - name: Invalidate CloudFront Cache
        env:
          DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
